language: ruby
rvm:
  - 2.0.0
env:
  - DB=sqlite
  - DB=mysql 
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
before_script:
  - "export DISPLAY=:99.0"
  - "export APP_HOST=localhost"
  - "export PORT=9292"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - "rackup &"
  - sleep 3
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database placman_test'
  
bundler_args: --binstubs=./bundler_stubs